import React from "react";
import "./globals.css";
import { Outfit } from 'next/font/google';
import Navbar from "../components/navbar";
import Footer from "../components/footer";



const fontOutfit = Outfit({ subsets: ['latin'], 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${fontOutfit.className} bg-white`}>
          <Navbar />
          {children}
          <Footer />
      </body>
    </html>
  );
}
